/**
 * Vendors the two webfonts the game uses into public/fonts/.
 *
 * Both are SIL Open Font License, so they can be redistributed with the game.
 * Rather than pull Google's full Japanese fonts (8 MB+ each, split across a
 * hundred unicode-range chunks), this requests a `text=` subset containing only
 * the glyphs the UI actually draws, which comes back as one small woff2.
 *
 * Re-run with `node tools/fetch-fonts.mjs` after adding new Japanese UI text.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const OUT = path.join(process.cwd(), 'public', 'fonts');

/**
 * Every non-ASCII glyph the interface can draw. Kept explicit so the subset
 * stays tiny and so a missing glyph is a visible, fixable omission.
 */
const GLYPHS = [
  // Title, signage and lanterns
  '東方夜雀食堂営業中',
  // Menu and navigation
  '開店再献立帖設定続行戻閉始終了保存記録図鑑',
  // Day / night, time, money
  '昼夜朝晩時分日目当店主客数金銭円貫文値段',
  // Cooking
  '料理飲物調味酒肴焼煮蒸揚切鍋網皿箸盛付味',
  // Ratings and reactions
  '最高上出来普通不満怒喜楽美味不味絶品',
  // Places
  '妖怪道人里博麗神社紅魔館迷竹林白玉楼魔法森山旧地獄命蓮寺神霊廟太陽畑輝針城月都界',
  // Misc UI
  '評価順位合計収入支出利益達成条件報酬素材在庫買売',
  // Kana
  'あいうえおかきくけこさしすせそたちつてとなにぬねの',
  'はひふへほまみむめもやゆよらりるれろわをん',
  'アイウエオカキクケコサシスセソタチツテトナニヌネノ',
  'ハヒフヘホマミムメモヤユヨラリルレロワヲン',
  'がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽ',
  'ガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポ',
  'ゃゅょっーゞ々ャュョッ',
  // Punctuation and symbols
  '、。「」『』・！？〜（）：￥※★☆〇◎△▲▽▼',
].join('');

const ASCII = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('');
const SUBSET = [...new Set([...ASCII, ...GLYPHS])].join('');

const FAMILIES = [
  { css: 'Shippori+Mincho:wght@500;700;800', file: 'shippori-mincho', label: 'Shippori Mincho' },
  { css: 'Zen+Maru+Gothic:wght@400;500;700', file: 'zen-maru-gothic', label: 'Zen Maru Gothic' },
];

// Google serves woff2 only to user agents it believes support it.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const get = async (url, asText = true) => {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asText ? res.text() : Buffer.from(await res.arrayBuffer());
};

async function main() {
  mkdirSync(OUT, { recursive: true });
  const faces = [];

  for (const family of FAMILIES) {
    const cssUrl =
      `https://fonts.googleapis.com/css2?family=${family.css}` +
      `&text=${encodeURIComponent(SUBSET)}&display=swap`;
    const css = await get(cssUrl);

    // Each @font-face block carries its own weight and source URL.
    const blocks = css.split('@font-face').slice(1);
    let index = 0;
    for (const block of blocks) {
      const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
      // Subset URLs are of the form /l/font?kit=… with no file extension.
      const src = /url\((https:\/\/[^)]+)\)/.exec(block)?.[1];
      if (!src) continue;

      const name = `${family.file}-${weight}.woff2`;
      const bytes = await get(src, false);
      writeFileSync(path.join(OUT, name), bytes);
      faces.push({ family: family.label, weight, file: name, bytes: bytes.length });
      console.log(`  ${name.padEnd(30)} ${(bytes.length / 1024).toFixed(1)} KB`);
      index++;
    }
    if (index === 0) throw new Error(`no @font-face blocks parsed for ${family.label}`);
  }

  // A stylesheet the page can link locally, with no network dependency.
  const stylesheet = faces
    .map(
      (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./${f.file}') format('woff2');
}`,
    )
    .join('\n\n');
  writeFileSync(path.join(OUT, 'fonts.css'), `${stylesheet}\n`);

  writeFileSync(
    path.join(OUT, 'LICENSE.md'),
    `# Bundled fonts

Both families are licensed under the SIL Open Font License 1.1, which permits
bundling and redistribution with this project.

| Family | Designer | License |
| --- | --- | --- |
| Shippori Mincho | FONTDASU | [OFL 1.1](https://openfontlicense.org/) |
| Zen Maru Gothic | Yoshimichi Ohira | [OFL 1.1](https://openfontlicense.org/) |

The files here are glyph subsets covering only the characters the interface
draws, generated by \`tools/fetch-fonts.mjs\`. Regenerate them after adding new
Japanese text to the UI.
`,
  );

  const total = faces.reduce((sum, f) => sum + f.bytes, 0);
  console.log(`\n${faces.length} faces, ${(total / 1024).toFixed(1)} KB total`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
