// GENERATED by tools/build-data.mjs — do not edit by hand.
// Regenerate with `npm run build:data`.

export type Release =
  | "BaseGame"
  | "DLC1"
  | "DLC2"
  | "DLC3"
  | "DLC4"
  | "DLC5";

export type CuisineTag =
  | "Dark Matter"
  | "Expensive"
  | "Economical"
  | "Large Portion"
  | "Meat"
  | "Aquatic"
  | "Vegetarian"
  | "Homecooking"
  | "Premium"
  | "Legendary"
  | "Greasy"
  | "Mild"
  | "Good w/ Alcohol"
  | "Filling"
  | "Mountain Delicacy"
  | "Sea Delicacy"
  | "Japanese"
  | "Western"
  | "Chinese"
  | "Salty"
  | "Fresh"
  | "Sweet"
  | "Raw"
  | "Signature"
  | "Photogenic"
  | "Refreshing"
  | "Hot"
  | "Strength-Boosting"
  | "Peculiar"
  | "Cultural Heritage"
  | "Fungus"
  | "Wonderful"
  | "Small Portion"
  | "Dreamy"
  | "Specialty"
  | "Fruity"
  | "Soup"
  | "Grilled"
  | "Spicy"
  | "Aura-Bursting"
  | "Sour"
  | "Poison"
  | "Trend - Popular"
  | "Trend - Unpopular"
  | "Divine Punishment";

export type BeverageTag =
  | "No Alcohol"
  | "Low Alcohol"
  | "Mid Alcohol"
  | "High Alcohol"
  | "Chillable"
  | "Heatable"
  | "Shochu"
  | "Sake"
  | "Cocktail"
  | "Western"
  | "Liquor"
  | "Beer"
  | "Neat"
  | "Fruity"
  | "Sweet"
  | "Dry"
  | "Bitter"
  | "Soda"
  | "Vintage"
  | "Modern"
  | "Stimulating";

export type FoodTag = CuisineTag | BeverageTag;

export type Kitchenware =
  | "Any"
  | "Boiling Pot"
  | "Cutting Board"
  | "Frying Pan"
  | "Grill"
  | "Steamer";

export type AlcoholStrength =
  | "High Alcohol"
  | "Low Alcohol"
  | "Mid Alcohol"
  | "No Alcohol";

export interface Cuisine {
  name: string;
  level: number;
  /** Base price in yen, before ingredient value and modifiers. */
  cost: number;
  /** Innate ("pink") tags, always present on the dish. */
  props: CuisineTag[];
  /** Forbidden ("black") tags — adding one turns the dish into Dark Matter. */
  xprops: CuisineTag[];
  /** Ingredients the recipe itself consumes. */
  ingredients: string[];
  kitchenware: Kitchenware;
  /** Seconds of cooking on the station. */
  cookTime: number;
  release: Release;
}

export interface Ingredient {
  name: string;
  level: number;
  /** Purchase/наценка value in yen; also what it adds to a dish's bill. */
  value: number;
  /** Every tag here is applied to a dish the ingredient is added to. */
  props: CuisineTag[];
  category: string;
  release: Release;
}

export interface Beverage {
  name: string;
  level: number;
  cost: number;
  alcohol: AlcoholStrength;
  /** Includes the alcohol strength, which customers can request directly. */
  props: BeverageTag[];
  release: Release;
}

export interface CommonCustomer {
  name: string;
  kind: 'common';
  locations: string[];
  prefCuisine: CuisineTag[];
  prefBeverage: BeverageTag[];
  description: string;
  release: Release;
}

export interface RareCustomer {
  name: string;
  kind: 'rare' | 'special';
  shortName: string;
  budget: { min: number; max: number };
  locations: string[];
  prefCuisine: CuisineTag[];
  dislikeCuisine: CuisineTag[];
  prefBeverage: BeverageTag[];
  release: Release;
}

export type Customer = CommonCustomer | RareCustomer;

export interface GameLocation {
  name: string;
  release: Release;
  rares: string[];
}

export interface MerchantStock {
  type: string;
  probability: number;
  amount: { lower: number; upper: number };
}

export interface Merchant {
  name: string;
  location: string;
  priceMultiplier: { lower: number; upper: number };
  itemOrder: string[];
  items: Record<string, MerchantStock>;
  release: Release;
}

export interface Partner {
  name: string;
  shortName: string;
  movementSpeed: string;
  workSpeed: string;
  /** Percent of the night's revenue this partner takes. */
  revenueShare: number;
  release: Release;
}

export interface TagEntry {
  name: string;
  id: number;
}

export interface TagTable {
  cuisine: TagEntry[];
  beverage: TagEntry[];
  /** [winner, loser] — the loser is struck from a resolved dish. */
  priority: [CuisineTag, CuisineTag][];
  trend: { popular: CuisineTag; unpopular: CuisineTag };
  thresholds: { expensiveAbove: number; economicalBelow: number; maxIngredients: number };
}
